### PR TITLE
update: flake inputs `bitcoin-core-cirrus-runner` and `nixpkgs`

### LINKED ISSUE #3: Upgrading to a newer nixos-unstable branch fails: `curl: (6) Could not resolve host: github.com`
While upgrading the nixos package flake input, I noticed that CI jobs that fetch from `github.com` fail as it can't resolve github.com. 

This can be resolved with https://github.com/bitcoin/bitcoin/issues/31889#issuecomment-2671844275 which makes me think it's an IPv6 issue. However, it would be good to find out why it actually fails. By bisecting nixpkgs, I found that https://github.com/NixOS/nixpkgs/commit/22ad67eebbeb281dfdc2db434dc7840b6105d105 is the first bad commit.

```commit
commit 22ad67eebbeb281dfdc2db434dc7840b6105d105 (HEAD)
Author: Sergei Trofimovich <slyich@gmail.com>
Date:   Fri Nov 8 22:10:36 2024 +0000

    iptables: 1.8.10 -> 1.8.11

    Changes: https://lore.kernel.org/netdev/Zy4nCFxZvkkUrjj6@orbyte.nwl.cc/T/

 pkgs/os-specific/linux/iptables/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

Now it would be good to explore why the iptables update breaks this.

### PR DESCRIPTION
**Pull request by 0xB10C**
The first commit closes #3 and allows us to upgrade `nixpkgs` again.

### CODE REVIEW

**Comment by 0xB10C** [comment]
```
error: builder for '/nix/store/my6h9fzs64fpylb8xr2iqcy6vk5xprin-linux-6.12.19.drv' failed with exit code 2;
       last 25 log lines:
       >       | ^
       > compilation terminated.
       > make[6]: *** [../scripts/Makefile.build:229: drivers/infiniband/hw/mlx5/mem.o] Error 1
       > make[6]: *** Waiting for unfinished jobs....
       > ../drivers/infiniband/hw/mlx5/main.c:4967:1: fatal error: error writing to /build/ccOHDxeX.s: No space left on device
       >  4967 | module_exit(mlx5_ib_cleanup);
       >       | ^~~~~~~~~~~
       > compilation terminated.
       > make[6]: *** [../scripts/Makefile.build:229: drivers/infiniband/hw/mlx5/main.o] Error 1
       > ../drivers/infiniband/hw/mlx5/mr.c:2866:1: fatal error: error writing to /build/cceVrUY1.s: No space left on device
       >  2866 | }
       >       | ^
       > compilation terminated.
       > make[6]: *** [../scripts/Makefile.build:229: drivers/infiniband/hw/mlx5/mr.o] Error 1
       > ../drivers/infiniband/hw/mlx5/qp.c:5845:1: fatal error: error writing to /build/cc4E7AMp.s: No space left on device
       >  5845 | }
       >       | ^
       > compilation terminated.
       > make[6]: *** [../scripts/Makefile.build:229: drivers/infiniband/hw/mlx5/qp.o] Error 1
       > make[5]: *** [../scripts/Makefile.build:478: drivers/infiniband/hw/mlx5] Error 2
       > make[4]: *** [../scripts/Makefile.build:478: drivers/infiniband/hw] Error 2
       > make[3]: *** [../scripts/Makefile.build:478: drivers/infiniband] Error 2
       > make[2]: *** [../scripts/Makefile.build:478: drivers] Error 2
       > make[1]: *** [/build/linux-6.12.19/Makefile:1944: .] Error 2
       > make: *** [../Makefile:224: __sub-make] Error 2
       For full logs, run 'nix log /nix/store/my6h9fzs64fpylb8xr2iqcy6vk5xprin-linux-6.12.19.drv'.
       note: build failure may have been caused by lack of free disk space
```
